name: Build and Test

on:
  push:
    branches:
      - main

jobs:
  build_and_test:
    name: Build Docker Image and Run Tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t svm-api .

    - name: Run Tests
      run: docker run --rm svm-api pytest
